nav:
- intro.md
- core.md
- constraints.md
- normalization.md
- joins.md
- set.md
- grouping-aggregation.md
- subquery.md
- conditional.md
- cte.md
- window-function.md
- data-transformation.md
- json.md
- views.md
- variables.md
- function.md
- stored-procedure.md
- dynamic-sql.md
- trigger.md
- transactions.md
- indexes.md
- execution-plan.md
- profiling.md
- optimization.md
- performance.md
- security.md
- partitioning-sharding.md
- replication-mirroring.md